package com.gewujie.zibian.model;

import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for User entity
 * Tests @PrePersist, @PreUpdate callbacks and field validations
 */
public class UserTest {

    /**
     * Test @PrePersist callback execution
     * Validates: Requirements 1.1, 5.1
     */
    @Test
    public void testPrePersistGeneratesUuid() {
        User user = new User();
        user.setNickname("TestUser");
        
        assertNull(user.getUuid(), "UUID should be null before onCreate");
        
        // Manually trigger @PrePersist
        user.onCreate();
        
        assertNotNull(user.getUuid(), "UUID should be generated by onCreate");
        assertNotNull(user.getCreatedAt(), "createdAt should be set by onCreate");
        assertNotNull(user.getUpdatedAt(), "updatedAt should be set by onCreate");
    }

    /**
     * Test @PrePersist does not override existing UUID
     * Validates: Requirements 5.1, 5.2
     */
    @Test
    public void testPrePersistPreservesExistingUuid() {
        User user = new User();
        user.setNickname("TestUser");
        String existingUuid = "550e8400-e29b-41d4-a716-446655440000";
        user.setUuid(existingUuid);
        
        user.onCreate();
        
        assertEquals(existingUuid, user.getUuid(), "Existing UUID should be preserved");
    }

    /**
     * Test @PreUpdate callback execution
     * Validates: Requirements 1.1
     */
    @Test
    public void testPreUpdateUpdatesTimestamp() throws InterruptedException {
        User user = new User();
        user.setNickname("TestUser");
        user.onCreate();
        
        LocalDateTime originalUpdatedAt = user.getUpdatedAt();
        
        // Wait a bit to ensure timestamp difference
        Thread.sleep(10);
        
        // Trigger @PreUpdate
        user.onUpdate();
        
        assertNotNull(user.getUpdatedAt(), "updatedAt should still be set");
        assertTrue(user.getUpdatedAt().isAfter(originalUpdatedAt), "updatedAt should be after original timestamp");
    }

    /**
     * Test phone field accepts null values
     * Validates: Requirements 2.4
     */
    @Test
    public void testPhoneFieldAcceptsNull() {
        User user = new User();
        user.setNickname("TestUser");
        user.setPhone(null);
        user.onCreate();
        
        assertNull(user.getPhone(), "Phone should be null");
        assertNotNull(user.getUuid(), "UUID should still be generated");
    }

    /**
     * Test phone field accepts valid phone numbers
     * Validates: Requirements 2.1, 2.3
     */
    @Test
    public void testPhoneFieldAcceptsValidPhones() {
        String[] validPhones = {
            "13800138000",
            "13900139000",
            "15800158000",
            "17800178000",
            "18800188000"
        };
        
        for (String phone : validPhones) {
            User user = new User();
            user.setNickname("TestUser");
            user.setPhone(phone);
            user.onCreate();
            
            assertEquals(phone, user.getPhone(), "Phone should be set correctly");
            assertNotNull(user.getUuid(), "UUID should be generated");
        }
    }

    /**
     * Test all fields are properly initialized
     */
    @Test
    public void testDefaultFieldValues() {
        User user = new User();
        user.onCreate();
        
        assertNotNull(user.getUuid(), "UUID should be generated");
        assertNull(user.getNickname(), "Nickname should be null by default");
        assertNull(user.getPhone(), "Phone should be null by default");
        assertNull(user.getAvatar(), "Avatar should be null by default");
        assertFalse(user.getIsVip(), "isVip should be false by default");
        assertNotNull(user.getCreatedAt(), "createdAt should be set");
        assertNotNull(user.getUpdatedAt(), "updatedAt should be set");
    }

    /**
     * Test VIP status can be set
     */
    @Test
    public void testVipStatus() {
        User user = new User();
        user.setIsVip(true);
        user.onCreate();
        
        assertTrue(user.getIsVip(), "VIP status should be true");
        assertNotNull(user.getUuid(), "UUID should still be generated");
    }
}
