package com.gewujie.zibian.model;

import org.junit.jupiter.api.Test;
import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for User entity
 * Tests @PrePersist, @PreUpdate callbacks and field validations
 */
public class UserTest {

    /**
     * Test @PrePersist callback execution
     * Validates: Requirements 1.1, 5.1
     */
    @Test
    public void testPrePersistGeneratesUuid() {
        User user = new User();
        user.setNickname("TestUser");
        
        assertNull("UUID should be null before onCreate", user.getUuid());
        
        // Manually trigger @PrePersist
        user.onCreate();
        
        assertNotNull("UUID should be generated by onCreate", user.getUuid());
        assertNotNull("createdAt should be set by onCreate", user.getCreatedAt());
        assertNotNull("updatedAt should be set by onCreate", user.getUpdatedAt());
    }

    /**
     * Test @PrePersist does not override existing UUID
     * Validates: Requirements 5.1, 5.2
     */
    @Test
    public void testPrePersistPreservesExistingUuid() {
        User user = new User();
        user.setNickname("TestUser");
        String existingUuid = "550e8400-e29b-41d4-a716-446655440000";
        user.setUuid(existingUuid);
        
        user.onCreate();
        
        assertEquals("Existing UUID should be preserved", 
                    existingUuid, user.getUuid());
    }

    /**
     * Test @PreUpdate callback execution
     * Validates: Requirements 1.1
     */
    @Test
    public void testPreUpdateUpdatesTimestamp() throws InterruptedException {
        User user = new User();
        user.setNickname("TestUser");
        user.onCreate();
        
        LocalDateTime originalUpdatedAt = user.getUpdatedAt();
        
        // Wait a bit to ensure timestamp difference
        Thread.sleep(10);
        
        // Trigger @PreUpdate
        user.onUpdate();
        
        assertNotNull("updatedAt should still be set", user.getUpdatedAt());
        assertTrue("updatedAt should be after original timestamp",
                  user.getUpdatedAt().isAfter(originalUpdatedAt));
    }

    /**
     * Test phone field accepts null values
     * Validates: Requirements 2.4
     */
    @Test
    public void testPhoneFieldAcceptsNull() {
        User user = new User();
        user.setNickname("TestUser");
        user.setPhone(null);
        user.onCreate();
        
        assertNull("Phone should be null", user.getPhone());
        assertNotNull("UUID should still be generated", user.getUuid());
    }

    /**
     * Test phone field accepts valid phone numbers
     * Validates: Requirements 2.1, 2.3
     */
    @Test
    public void testPhoneFieldAcceptsValidPhones() {
        String[] validPhones = {
            "13800138000",
            "13900139000",
            "15800158000",
            "17800178000",
            "18800188000"
        };
        
        for (String phone : validPhones) {
            User user = new User();
            user.setNickname("TestUser");
            user.setPhone(phone);
            user.onCreate();
            
            assertEquals("Phone should be set correctly", phone, user.getPhone());
            assertNotNull("UUID should be generated", user.getUuid());
        }
    }

    /**
     * Test all fields are properly initialized
     */
    @Test
    public void testDefaultFieldValues() {
        User user = new User();
        user.onCreate();
        
        assertNotNull("UUID should be generated", user.getUuid());
        assertNull("Nickname should be null by default", user.getNickname());
        assertNull("Phone should be null by default", user.getPhone());
        assertNull("Avatar should be null by default", user.getAvatar());
        assertFalse("isVip should be false by default", user.getIsVip());
        assertNotNull("createdAt should be set", user.getCreatedAt());
        assertNotNull("updatedAt should be set", user.getUpdatedAt());
    }

    /**
     * Test VIP status can be set
     */
    @Test
    public void testVipStatus() {
        User user = new User();
        user.setIsVip(true);
        user.onCreate();
        
        assertTrue("VIP status should be true", user.getIsVip());
        assertNotNull("UUID should still be generated", user.getUuid());
    }
}
